var data = {
  bname: "2021 Financials",
  currency: "$",
  currencyformat: "before",
  categories: [
    {
      id: 1,
      category: "Home",
      available: 100,
      assigned: 55,
      activity: 78,
      timing: "Monthly",
      enddate: 2,
      subcat: "Garden",
    },
    {
      id: 2,
      category: "Entertaintment",
      available: 100,
      assigned: 55,
      activity: 98,
      timing: "Yearly",
      enddate: "July",
      subcat: "Netflix",
    },
    {
      id: 3,
      category: "Recreation",
      available: 100,
      assigned: 55,
      activity: 29,
      timing: "Monthly",
      enddate: 19,
      subcat: "Gym",
    },
    {
      id: 4,
      category: "Food",
      available: 100,
      assigned: 55,
      activity: 33,
      timing: "Yearly",
      enddate: "October",
      subcat: "Icecream",
    },
    {
      id: 5,
      category: "Education",
      available: 100,
      assigned: 55,
      activity: 76,
      timing: "Yearly",
      enddate: "September",
      subcat: "Tuition",
    },
    {
      id: 6,
      category: "Auto",
      available: 100,
      assigned: 55,
      activity: 81,
      timing: "Weekly",
      enddate: "Saturday",
      subcat: "Oil",
    },

    // {
    //   id: 7,
    //   category: "Rent",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Monthly",
    //   enddate: 2,
    // },
    // {
    //   id: 8,
    //   category: "Internet",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Yearly",
    //   enddate: "July",
    // },
    // {
    //   id: 9,
    //   category: "Gym",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Monthly",
    //   enddate: 19,
    // },
    // {
    //   id: 10,
    //   category: "Recreation",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Yearly",
    //   enddate: "October",
    // },
    // {
    //   id: 11,
    //   category: "Insurance",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Yearly",
    //   enddate: "September",
    // },
    // {
    //   id: 12,
    //   category: "Groceries",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Weekly",
    //   enddate: "Saturday",
    // },
  ],
};

const fakedata = {
  bname: "2021 Financials",
  currency: "$",
  currencyformat: "before",
  categories: {
    Home: [
      {
        id: 1,
        category: "Home",
        available: 100,
        assigned: 55,
        timing: "Monthly",
        enddate: 2,
        subcat: "Garden",
      },
      {
        id: 2,
        category: "Entertaintment",
        available: 100,
        assigned: 55,
        timing: "Yearly",
        enddate: "July",
        subcat: "Netflix",
      },
    ],
    Recreation: [
      {
        id: 3,
        category: "Recreation",
        available: 100,
        assigned: 55,
        timing: "Monthly",
        enddate: 19,
        subcat: "Gym",
      },
      {
        id: 4,
        category: "Food",
        available: 100,
        assigned: 55,
        timing: "Yearly",
        enddate: "October",
        subcat: "Icecream",
      },
    ],
    Education: [
      {
        id: 5,
        category: "Education",
        available: 100,
        assigned: 55,
        timing: "Yearly",
        enddate: "September",
        subcat: "Tuition",
      },
      {
        id: 6,
        category: "Auto",
        available: 100,
        assigned: 55,
        timing: "Weekly",
        enddate: "Saturday",
        subcat: "Oil",
      },
    ],

    // {
    //   id: 7,
    //   category: "Rent",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Monthly",
    //   enddate: 2,
    // },
    // {
    //   id: 8,
    //   category: "Internet",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Yearly",
    //   enddate: "July",
    // },
    // {
    //   id: 9,
    //   category: "Gym",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Monthly",
    //   enddate: 19,
    // },
    // {
    //   id: 10,
    //   category: "Recreation",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Yearly",
    //   enddate: "October",
    // },
    // {
    //   id: 11,
    //   category: "Insurance",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Yearly",
    //   enddate: "September",
    // },
    // {
    //   id: 12,
    //   category: "Groceries",
    //   available: 100,
    //   assigned: 55,
    //   timing: "Weekly",
    //   enddate: "Saturday",
    // },
  },
};
module.exports = data;
